swnat/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from nurseapp import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^403/', views.error403),
    url(r'^$', auth_views.LoginView.as_view(), name='login'),

    # user auth
    # url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    url(r'^home2/$', views.home2, name='home'),
    url(r'^patient_historics/$', views.patient_historics, name='patient_historics'),

    # url(r'^publico/$', views.panel_publico, name='panel_publico'),

    url(r'^patients/$', views.adm_patient, name='patient_list'),
    url(r'^patients/add/$', views.adm_patient_add, name='patient_add'),
    url(r'^patients/edit/$', views.adm_patient_mod, name='patient_edit'),
    url(r'^patients/delete/$', views.adm_patient_del, name='patient_del'),

    url(r'^records/$', views.adm_record, name='record_list'),
    url(r'^records/add/$', views.adm_record_add, name='record_add'),
    url(r'^records/edit/$', views.adm_record_mod, name='record_edit'),
    url(r'^records/delete/$', views.adm_record_del, name='record_del'),

    url(r'^ranges/$', views.adm_range, name='range_list'),
    url(r'^ranges/add/$', views.adm_range_add, name='range_add'),
    url(r'^ranges/edit/$', views.adm_range_mod, name='range_edit'),
    url(r'^ranges/delete/$', views.adm_range_del, name='range_del'),

]

nurseapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.db import IntegrityError
import datetime


class Patient(models.Model):
    nurse = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    genders = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=genders)
    cid = models.IntegerField(unique=True)
    birth = models.DateField()
    age = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return '%s %s' % (self.name, self.lastname)


class Record(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    # date = models.DateField(default=datetime.date.today)
    date = models.DateTimeField(default=datetime.datetime.now)
    pressure1 = models.IntegerField()
    pressure2 = models.IntegerField()
    bpm = models.IntegerField()
    status_pressure = models.CharField(max_length=10, default='', blank=True)
    status_bpm = models.CharField(max_length=10, default='', blank=True)

    # vitals = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return 'for %s %s' % (self.patient.name, self.patient.lastname)


class RangeP1(models.Model):
    pressure1_min = models.IntegerField()
    pressure1_max = models.IntegerField()
    level = models.IntegerField(unique=True)
    status = models.CharField(max_length=25)


class RangeP2(models.Model):
    pressure2_min = models.IntegerField()
    pressure2_max = models.IntegerField()
    level = models.IntegerField(unique=True)
    status = models.CharField(max_length=25)


class RangeB(models.Model):
    age = models.IntegerField()
    genders = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=genders)
    bpm_min = models.IntegerField()
    bpm_max = models.IntegerField()
    status = models.CharField(max_length=25)


class Range(models.Model):
    age = models.IntegerField()
    genders = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=genders)
    bpm_min = models.IntegerField()
    bpm_max = models.IntegerField()
    pressure1_min = models.IntegerField()
    pressure1_max = models.IntegerField()
    pressure2_min = models.IntegerField()
    pressure2_max = models.IntegerField()

nurseapp/views/patient_historics.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from nurseapp.forms import *
from .records import record_eval_function


def patient_historics(request):
    """
    Vista que procesa la solicitud de visualizar y eliminar records
    """
    search = ''
    message = ''
    name = ''
    objects = {}
    print(request)
    if request.GET.get('search'):
        search = request.GET.get('search')
        objects = Record.objects.filter(patient__cid=request.GET.get("search")).order_by('date')
        if objects:
            name = objects.first().patient.name + ' ' + objects.first().patient.lastname
            objects = record_eval_function(objects)
        else:
            message = 'Not found...'

    return render(request, "patient_historics.html",
                  {'objects': objects, 'message': message, 'name': name, 'search': search})

templates/base.html
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NurseApp</title>
    <!-- Custom fonts for this template -->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="/static/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

    {% comment %}   <!-- Bootstrap Core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="/static/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/static/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    <!-- DataTables Buttons CSS -->
    <link href="/static/vendor/datatables-buttons/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/datatables-buttons/buttons.dataTables.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    {% endcomment %}
</head>

<body id="page-top">

<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/home2/">
            <div class="sidebar-brand-icon">
                <img src="/static/nurse.png" width="30" height="30">
            </div>
            <div class="sidebar-brand-text mx-3">NurseApp</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="/home2/">
                <i class="fas fa-fw fa-home"></i>
                <span>Home</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        {% comment %}<!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>{% endcomment %}
        {% if perms.nurseapp.view_patient %}
            <li class="nav-item">
                <a class="nav-link" href="/patients">
                    <i class="fas fa-fw fa-user"></i>
                    <span>Patients</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/records">
                    <i class="fas fa-fw fa-file"></i>
                    <span>Records</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/ranges">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Ranges</span></a>
            </li>

        {% endif %}
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">username</span>
                                <img class="img-profile rounded-circle"
                                     src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                        <ul class="nav navbar-top-links navbar-right">
                            <li><a href="{% url 'patient_historics' %}">Patient Historics</a></li>
                        </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">


                    <!-- Navigation -->
                    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="/home2/"><img src="/static/nurse.png" width="30" height="30"
                                                                        style="vertical-align: middle;display: inline-block;">
                                NurseApp</a>
                        </div>
                        <!-- /.navbar-header -->

                        <ul class="nav navbar-top-links navbar-right">
                            <li><a href="{% url 'patient_historics' %}">Patient Historics</a></li>
                            <!-- /.dropdown -->
                            {% if request.user.is_authenticated %}
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-user">
                                        <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Cerrar Sesion</a>
                                        </li>
                                    </ul>
                                    <!-- /.dropdown-user -->
                                </li>

                                <!-- /.dropdown -->
                                </ul>
                                <!-- /.navbar-top-links -->

                                <div class="navbar-default sidebar" role="navigation">
                                    <div class="sidebar-nav navbar-collapse">
                                        <ul class="nav" id="side-menu">

                                            <li>
                                                <a href="/home2"><i class="fa fa-home fa-fw"></i> Home </a>
                                            </li>


                                            {% if perms.nurseapp.view_patient %}
                                                <li>
                                                    <a href="/patients"><i class="fa fa-user  fa-fw"></i> Patients </a>
                                                </li>
                                                <li>
                                                    <a href="/records"><i class="fa fa-file-text  fa-fw"></i> Patient
                                                        Records </a>
                                                </li>
                                                <li>
                                                    <a href="/ranges"><i class="fa fa-list  fa-fw"></i> Ranges </a>
                                                </li>
                                            {% endif %}


                                        </ul>
                                        {% if messages %}
                                            <br>&emsp; INFO: </br>
                                        {% endif %}
                                        {% for message in messages %}
                                            <p>{{ message }}</p>
                                        {% endfor %}
                                    </div>
                                    <!-- /.sidebar-collapse -->
                                </div>
                                <!-- /.navbar-static-side -->

                            {% else %}
                                <li><a href="{% url 'login' %}">Login</a></li>
                            {% endif %}

                    </nav>


                    {% if request.user.is_authenticated %}
                        <div id="page-wrapper">
                    {% endif %}
                    {% block content %}{% endblock %}
                    {% if request.user.is_authenticated %}
                        </div>
                    {% endif %}

                </div>
                <!-- /#wrapper -->

                <!-- Bootstrap core JavaScript-->
                <script src="/static/vendor/jquery/jquery.min.js"></script>
                <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                <!-- Core plugin JavaScript-->
                <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

                <!-- Custom scripts for all pages-->
                <script src="/static/js/sb-admin-2.min.js"></script>

                <!-- Page level plugins -->
                <script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
                <script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                <script>
                    {% for message in messages %}
                        $(document).ready(function () {
                            $('.toast').toast('show');
                        });
                    {% endfor %}
                </script>
                {% comment %}
<!-- jQuery -->
<script src="/static/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/static/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="/static/vendor/raphael/raphael.min.js"></script>
    <script src="/static/vendor/morrisjs/morris.min.js"></script>
    <script src="/static/data/morris-data.js"></script>


<!-- Custom Theme JavaScript -->
<script src="/static/dist/js/sb-admin-2.js"></script>
{% endcomment %}

                {% block scripts %}{% endblock %}
</body>

</html>

templates/base2.html
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NurseApp</title>
    <!-- Custom fonts for this template -->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="/static/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

    {% comment %}   <!-- Bootstrap Core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="/static/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/static/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    <!-- DataTables Buttons CSS -->
    <link href="/static/vendor/datatables-buttons/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/datatables-buttons/buttons.dataTables.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    {% endcomment %}
</head>

<body id="page-top">

<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center"
           {% if request.user.is_authenticated %}href="/home2/"{% else %} href="/patient_historics"{% endif %}>
            <div class="sidebar-brand-icon">
                <img src="/static/nurse.png" width="30" height="30">
            </div>
            <div class="sidebar-brand-text mx-3">NurseApp</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        {% if request.user.is_authenticated %}
            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="/home2/">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Home</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">



            {% if perms.nurseapp.view_patient %}
                <li class="nav-item">
                    <a class="nav-link" href="/patients">
                        <i class="fas fa-fw fa-user"></i>
                        <span>Patients</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/records">
                        <i class="fas fa-fw fa-file"></i>
                        <span>Records</span></a>
                </li>

            {% endif %}
                {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="/ranges">
                            <i class="fas fa-fw fa-list"></i>
                            <span>Ranges</span></a>
                    </li>
                {% endif %}
                <hr class="sidebar-divider d-none d-md-block">

        {% endif %}

        {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'patient_historics' %}">
                    <i class="fas fa-fw fa-chart-bar"></i>
                    <span>Patient History</span></a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'patient_historics' %}">
                    <i class="fas fa-fw fa-user-alt"></i>
                    <span>Patients Area</span></a>
            </li>
        {% endif %}
        <hr class="sidebar-divider">
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

        {% include 'message.html' %}

    </ul>
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small"> {{ request.user }}</span>
                            <i class="fas fa-fw fa-user"></i>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="/logout">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>


            </nav>
            <!-- End of Topbar -->


            <!-- Begin Page Content -->
            <div class="container-fluid">
                <div id="page-wrapper">
                    {% block content %}{% endblock %}
                </div>
            </div>

        </div>
        <!-- /#wrapper -->

        <!-- Bootstrap core JavaScript-->
        <script src="/static/vendor/jquery/jquery.min.js"></script>
        <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="/static/js/sb-admin-2.min.js"></script>

        <!-- Page level plugins -->
        <script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
        <script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

        <script src="/static/vendor/datatables-buttons/dataTables.buttons.min.js"></script>
        <script src="/static/vendor/datatables-buttons/buttons.bootstrap4.min.js"></script>

        <script>
            {% for message in messages %}
                $(document).ready(function () {
                    $('.toast').toast('show');
                });
            {% endfor %}
        </script>

        {% block scripts %}{% endblock %}
</body>

</html>

templates/home2.html
{% extends "base2.html" %}
{% load auth_extras %}
<body>
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Welcome, {{ request.user }}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    {% if perms.nurseapp.view_patient %}
        <div class="row">
            <div onclick="document.location.href = '/patients/'; return false" class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a
                                        href="/patients/">Patients</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ lista.patients }}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div onclick="document.location.href = '/records/'; return false" class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a
                                        href="/records/">Records</a></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ lista.records }}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-file fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Last patient records overview</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                        <tr>
                            <th>Date Recorded</th>
                            <th>Patient Name</th>
                            <th>Patient Age</th>
                            <th>Blood pressure</th>
                            <th>Heartrate</th>
                            <th>Vitals</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in objects %}
                            <tr class="odd gradeX">
                                <td>{{ object.date|date:"M d, Y H:i" }}</td>
                                <td>{{ object.patient.name }} {{ object.patient.lastname }}</td>
                                <td>{{ object.patient.age }}</td>
                                <td>{{ object.pressure1 }} - {{ object.pressure2 }} mmHg ({{ object.status_pressure }})
                                </td>
                                <td>{{ object.bpm }} BPM ({{ object.status_bpm }})</td>
                                <td>
                                    {% if object.status_pressure == "Normal" and object.status_bpm == "Normal" %}
                                        <a class="btn btn-success btn-circle"><i class="fas fa-check"></i></a>
                                    {% else %}
                                        <a class="btn btn-danger btn-circle"><i
                                                class="fas fa-exclamation-triangle"></i></a>
                                    {% endif %}
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}

    </div>


{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            //$.fn.dataTable.moment( 'MM/DD/YYYY h:mm:ss' );
            $('#dataTable').DataTable({
                responsive: true,
                "lengthMenu": [[25, 50, -1], [25, 50, "All"]],
                "order": [[0, "desc"]],
                "columnDefs": [
                    {"orderable": false, "targets": 5},
                ]
            });
        });
    </script>
{% endblock %}

templates/message.html
{% for message in messages %}
  <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-header">
      <strong class="mr-auto">
        {% if message.tags == 'error' %}
          <i class="fas fa-times mr-2"></i>
        {% elif message.tags == 'warning' %}
          <i class="fas fa-exclamation mr-2"></i>
        {% elif message.tags == 'info' %}
          <i class="fas fa-info mr-2"></i>
        {% elif message.tags == 'success' %}
          <i class="fas fa-check mr-2"></i>
        {% endif %}
        {{message.tags|capfirst}}
      </strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
        <p style="color:white">{{message|safe}}</p>
    </div>
  </div>
{% endfor %}