swnat/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from nurseapp import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^403/', views.error403),
    url(r'^$', auth_views.LoginView.as_view(), name='login'),

    # user auth
    # url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    url(r'^home2/$', views.home2, name='home'),
    url(r'^patient_historics/$', views.patient_historics, name='patient_historics'),

    # url(r'^publico/$', views.panel_publico, name='panel_publico'),

    url(r'^patients/$', views.adm_patient, name='patient_list'),
    url(r'^patients/add/$', views.adm_patient_add, name='patient_add'),
    url(r'^patients/edit/$', views.adm_patient_mod, name='patient_edit'),
    url(r'^patients/delete/$', views.adm_patient_del, name='patient_del'),

    url(r'^records/$', views.adm_record, name='record_list'),
    url(r'^records/add/$', views.adm_record_add, name='record_add'),
    url(r'^records/edit/$', views.adm_record_mod, name='record_edit'),
    url(r'^records/delete/$', views.adm_record_del, name='record_del'),

    url(r'^ranges/$', views.adm_range, name='range_list'),
    url(r'^ranges/add/$', views.adm_range_add, name='range_add'),
    url(r'^ranges/edit/$', views.adm_range_mod, name='range_edit'),
    url(r'^ranges/delete/$', views.adm_range_del, name='range_del'),

]

nurseapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.db import IntegrityError
import datetime


class Patient(models.Model):
    nurse = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    genders = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=genders)
    cid = models.IntegerField(unique=True)
    birth = models.DateField()
    age = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return '%s %s' % (self.name, self.lastname)


class Record(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    # date = models.DateField(default=datetime.date.today)
    date = models.DateTimeField(default=datetime.datetime.now)
    pressure1 = models.IntegerField()
    pressure2 = models.IntegerField()
    bpm = models.IntegerField()
    status_pressure = models.CharField(max_length=10, default='', blank=True)
    status_bpm = models.CharField(max_length=10, default='', blank=True)

    # vitals = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return 'for %s %s' % (self.patient.name, self.patient.lastname)


class RangeP1(models.Model):
    pressure1_min = models.IntegerField()
    pressure1_max = models.IntegerField()
    level = models.IntegerField(unique=True)
    status = models.CharField(max_length=25)


class RangeP2(models.Model):
    pressure2_min = models.IntegerField()
    pressure2_max = models.IntegerField()
    level = models.IntegerField(unique=True)
    status = models.CharField(max_length=25)


class RangeB(models.Model):
    age = models.IntegerField()
    genders = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=genders)
    bpm_min = models.IntegerField()
    bpm_max = models.IntegerField()
    status = models.CharField(max_length=25)


class Range(models.Model):
    age = models.IntegerField()
    genders = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=genders)
    bpm_min = models.IntegerField()
    bpm_max = models.IntegerField()
    pressure1_min = models.IntegerField()
    pressure1_max = models.IntegerField()
    pressure2_min = models.IntegerField()
    pressure2_max = models.IntegerField()

nurseapp/views/patients.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from nurseapp.forms import *
import datetime
from django.contrib import messages


# PLANTILLAS
@login_required
@permission_required('nurseapp.view_patient', raise_exception=True)
def adm_patient(request):
    """
    Vista que procesa la solicitud de visualizar y eliminar patients
    """
    if request.user.is_superuser:
        objects = Patient.objects.all()
    else:
        objects = Patient.objects.filter(nurse_id=request.user.id)

    today = datetime.date.today()

    for o in objects:
        o.age = today.year - o.birth.year - ((today.month, today.day) < (o.birth.month, o.birth.day))

    return render(request, "abm/patients.html", {'objects': objects})


@login_required
@permission_required('nurseapp.add_patient', raise_exception=True)
def adm_patient_add(request):
    """
    Vista que procesa la solicitud de crear patients
    """
    mensaje = ''
    if request.method == 'POST':
        if request.POST.get("save"):
            form = PatientForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.nurse = User.objects.get(pk=request.user.id)
                instance.save()
                mensaje = 'Patient \"' + instance.__str__() + '\" created'
                messages.add_message(request, messages.INFO, mensaje)
                # Log.objects.create(fecha=datetime.datetime.now(), usuario=request.user, accion="Crea patient \'"+instance.__str__()+"\'")
                return redirect("/patients/")
            else:
                print(form.errors)
                print('invalid')
        else:
            return redirect("/patients/")
    else:
        form = PatientForm(initial={'birth': '2000-01-01'})

    return render(request, "abm/patients/add.html", {'form': form, 'mensaje': mensaje})


@login_required
@permission_required('nurseapp.change_patient', raise_exception=True)
def adm_patient_mod(request):
    """
    Vista que procesa la solicitud de modificar patients
    """
    mensaje = ''
    if request.method == 'POST':
        if request.POST.get("edit"):
            if request.POST.get("object_id"):
                p = Patient.objects.get(pk=request.POST['object_id'])
                form = PatientForm(instance=p)
                object_id = request.POST.get("object_id")
                return render(request, "abm/patients/edit.html",
                              {'object_id': object_id, 'form': form, 'mensaje': mensaje})
            else:
                return redirect("/patients/")

        elif request.POST.get("save"):
            object_id = request.POST.get("object_id")
            p = Patient.objects.get(pk=request.POST['object_id'])
            form = PatientForm(request.POST, instance=p)
            if form.is_valid():
                instance = form.save()
                # Log.objects.create(fecha=datetime.datetime.now(), usuario=request.user, accion="Modifica patient \'" + instance.__str__() + "\'")
                mensaje = 'Patient saved'
                messages.add_message(request, messages.INFO, mensaje)
                return redirect("/patients/")
            else:
                print(form.errors)
                print('invalid')
        else:
            return redirect("/patients/")

    else:
        return redirect("/patients/")


@login_required
@permission_required('nurseapp.change_patient', raise_exception=True)
def adm_patient_del(request):
    """
    Vista que procesa la solicitud de eliminar patients
    """

    mensaje = ''
    if request.method == 'POST':
        if request.POST.get('object_id'):
            instance = Patient.objects.get(pk=request.POST['object_id'])
            if request.POST.get('delete'):
                form = PatientForm(instance=instance)
                for key in form.fields.keys():
                    if form.fields.get(key):
                        form.fields[key].widget.attrs['readonly'] = True
                return render(request, "abm/patients/delete.html",
                              {'form': form, 'object_id': request.POST.get('object_id')})
            if request.POST.get('delete_confirm'):
                instance = Patient.objects.get(pk=request.POST['object_id'])
                instance.delete()
                mensaje = 'Patient deleted'
                messages.add_message(request, messages.INFO, mensaje)

    return redirect("/patients/")

nurseapp/views/ranges.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from nurseapp.forms import *
import datetime
from django.contrib import messages


# PLANTILLAS
@login_required
@permission_required('nurseapp.view_range', raise_exception=True)
def adm_range(request):
    """
    Vista que procesa la solicitud de visualizar y eliminar ranges
    """
    objects = RangeP1.objects.all()
    objects2 = RangeP2.objects.all()
    objects3 = RangeB.objects.all()

    return render(request, "abm/ranges.html", {'objects': objects, 'objects2': objects2, 'objects3': objects3})


@login_required
@permission_required('nurseapp.add_range', raise_exception=True)
def adm_range_add(request):
    """
    Vista que procesa la solicitud de crear ranges
    """
    message = ''
    range_type = ''
    if request.method == 'POST':
        if request.POST.get("save"):

            if request.POST.get("type") == "p1":
                form = RangeP1Form(request.POST)
            if request.POST.get("type") == "p2":
                form = RangeP2Form(request.POST)
            if request.POST.get("type") == "b":
                form = RangeBForm(request.POST)

            if form.is_valid():
                instance = form.save()
                message = 'Range created'
                messages.add_message(request, messages.INFO, message)
                # Log.objects.create(fecha=datetime.datetime.now(), usuario=request.user, accion="Crea range \'"+instance.__str__()+"\'")
                return redirect("/ranges/")
            else:
                print(form.errors)
                print('invalid')
        else:
            return redirect("/ranges/")
    else:
        if request.GET.get("add"):
            range_type = request.GET.get("add")
            if range_type == 'p1':
                form = RangeP1Form()
            elif range_type == 'p2':
                form = RangeP2Form()
            elif range_type == 'b':
                form = RangeBForm()
        else:
            return redirect("/ranges/")

    return render(request, "abm/ranges/add.html", {'form': form, 'message': message, 'type': range_type})


@login_required
@permission_required('nurseapp.change_range', raise_exception=True)
def adm_range_mod(request):
    """
    Vista que procesa la solicitud de modificar ranges
    """
    message = ''
    range_type = ''
    if request.method == 'POST':
        if request.POST.get("edit"):
            range_type = request.POST.get("edit")
            if range_type == "p1":
                p = RangeP1.objects.get(pk=request.POST['object_id'])
                form = RangeP1Form(instance=p)
                object_id = request.POST.get("object_id")
                return render(request, "abm/ranges/edit.html",
                              {'object_id': object_id, 'form': form, 'message': message, 'type': range_type})
            if range_type == "p2":
                p = RangeP2.objects.get(pk=request.POST['object_id'])
                form = RangeP2Form(instance=p)
                object_id = request.POST.get("object_id")
                return render(request, "abm/ranges/edit.html",
                              {'object_id': object_id, 'form': form, 'message': message, 'type': range_type})
            if range_type == "b":
                p = RangeB.objects.get(pk=request.POST['object_id'])
                form = RangeBForm(instance=p)
                object_id = request.POST.get("object_id")
                return render(request, "abm/ranges/edit.html",
                              {'object_id': object_id, 'form': form, 'message': message, 'type': range_type})
            else:
                return redirect("/ranges/")

        elif request.POST.get("save"):
            object_id = request.POST.get("object_id")

            if request.POST.get("type") == "p1":
                p = RangeP1.objects.get(pk=request.POST['object_id'])
                form = RangeP1Form(request.POST, instance=p)
            if request.POST.get("type") == "p2":
                p = RangeP2.objects.get(pk=request.POST['object_id'])
                form = RangeP2Form(request.POST, instance=p)
            if request.POST.get("type") == "b":
                p = RangeB.objects.get(pk=request.POST['object_id'])
                form = RangeBForm(request.POST, instance=p)

            if form.is_valid():
                instance = form.save()
                # Log.objects.create(fecha=datetime.datetime.now(), usuario=request.user, accion="Modifica range \'" + instance.__str__() + "\'")
                message = 'Range saved'
                messages.add_message(request, messages.INFO, message)
                return redirect("/ranges/")
            else:
                print(form.errors)
                print('invalid')
        else:
            return redirect("/ranges/")
    else:
        return redirect("/ranges/")


@login_required
@permission_required('nurseapp.change_range', raise_exception=True)
def adm_range_del(request):
    """
    Vista que procesa la solicitud de eliminar ranges
    """
    range_type = ''
    message = ''
    if request.method == 'POST':
        if request.POST.get('delete'):
            range_type = request.POST.get("delete")
            if range_type == "p1":
                instance = RangeP1.objects.get(pk=request.POST['object_id'])
                form = RangeP1Form(instance=instance)
            if range_type == "p2":
                instance = RangeP2.objects.get(pk=request.POST['object_id'])
                form = RangeP2Form(instance=instance)
            if range_type == "b":
                instance = RangeB.objects.get(pk=request.POST['object_id'])
                form = RangeBForm(instance=instance)
            for key in form.fields.keys():
                if form.fields.get(key):
                    form.fields[key].widget.attrs['readonly'] = True
            return render(request, "abm/ranges/delete.html",
                          {'form': form, 'object_id': request.POST.get('object_id'), 'type': range_type})

        if request.POST.get('delete_confirm'):
            if request.POST.get("type") == "p1":
                instance = RangeP1.objects.get(pk=request.POST['object_id'])
            if request.POST.get("type") == "p2":
                instance = RangeP2.objects.get(pk=request.POST['object_id'])
            if request.POST.get("type") == "b":
                instance = RangeB.objects.get(pk=request.POST['object_id'])
            instance.delete()
            message = 'Range deleted'
            messages.add_message(request, messages.INFO, message)

    return redirect("/ranges/")

templates/abm/patients.html
{% extends "base2.html" %}
{% block content %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">My Patients</h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Patients</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Birthdate</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th class="all" width="35">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in objects %}
                        <tr class="odd gradeX">
                            <td>{{ object.cid }}</td>
                            <td>{{ object.lastname }}, {{ object.name }}</td>
                            <td>{{ object.birth }}</td>
                            <td>{{ object.age }}</td>
                            <td>{% if object.gender == "m" %}
                                Male
                            {% else %}
                                Female
                            {% endif %}</td>

                            <td>
                                <div style="display: flex;">
                                    <form action="/records/add">
                                        <input type="hidden" name="patient_id" value={{ object.pk }}>
                                        <button type="submit" formnovalidate
                                                class="btn btn-default">Record Vitals
                                        </button>
                                    </form>
                                    <form action="/patients/edit/" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="object_id" value={{ object.pk }}>
                                        <button type="submit" formnovalidate name="edit" value="a"
                                                class="btn btn-default">Edit
                                        </button>
                                    </form>
                                    <form id={{ object.pk }} action="/patients/delete/" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="object_id" value={{ object.pk }}>
                                        <input type="submit" class="btn btn-danger" formnovalidate name="delete"
                                               value="Delete"/>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if perms.nurseapp.add_patient %}
                    <form action="/patients/add/">
                        <input type="submit" value="Add a new Patient" class="btn btn-primary"/>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                responsive: true,
                "lengthMenu": [[25, 50, -1], [25, 50, "All"]],
                "columnDefs": [{"orderable": false, "targets": 5}]
            });
        });
    </script>

{% endblock %}

templates/abm/records.html
{% extends "base2.html" %}
{% block content %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Patient Records</h1>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Records {% if patient_name %} for {{ patient_name }}{% endif %}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                    <tr>
                        <th>Date</th>
                        <th>Patient ID</th>
                        <th>Patient Name</th>
                        <th>Patient Age</th>
                        <th>Blood pressure</th>
                        <th>Heartrate</th>
                        <th>Vitals</th>
                        <th class="all" width="10">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in objects %}
                        <tr class="odd gradeX">
                            <td>{{ object.date|date:"M d, Y H:i" }}</td>
                            <td>{{ object.patient.cid }}</td>
                            <td>{{ object.patient.name }} {{ object.patient.lastname }}</td>
                            <td>{{ object.patient.age }}</td>
                            <td>{{ object.pressure1 }} - {{ object.pressure2 }} mmHg ({{ object.status_pressure }})</td>
                            <td>{{ object.bpm }} BPM ({{ object.status_bpm }})</td>
                            <td>
                                {% if object.status_pressure == "Normal" and object.status_bpm == "Normal" %}
                                    <a class="btn btn-success btn-circle"><i class="fas fa-check"></i></a>
                                {% else %}
                                    <a class="btn btn-danger btn-circle"><i class="fas fa-exclamation-triangle"></i></a>
                                {% endif %}
                            </td>
                            <td>
                                <div style="display: flex;">
                                    <form action="/records/edit/" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="object_id" value={{ object.pk }}>
                                        <button type="submit" formnovalidate name="edit" value="a"
                                                class="btn btn-default">Edit
                                        </button>
                                    </form>
                                    <form id={{ object.pk }} action="/records/delete/" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="object_id" value={{ object.pk }}>
                                        <input type="submit" class="btn btn-danger" formnovalidate name="delete"
                                               value="Delete"/>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% if perms.nurseapp.add_record %}
                    <form action="/records/add/">
                        <input type="hidden" name="patient_id" value="{{ patient_id }}">
                        <input type="submit" value="Add a new Record" class="btn btn-primary"/>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>#}
{#    <script src="https://cdn.datatables.net/plug-ins/1.10.21/sorting/datetime-moment.js"></script>#}

    <script>
        $(document).ready(function () {
            //$.fn.dataTable.moment( 'MM/DD/YYYY h:mm:ss' );
            $('#dataTable').DataTable({
                responsive: true,
                "lengthMenu": [[25, 50, -1], [25, 50, "All"]],
                "order": [[0, "desc"]],
                "columnDefs": [
                    { "orderable": false, "targets": 6 },
                    { "orderable": false, "targets": 7 },
                ]
            });
        });
    </script>
{% endblock %}